name:                mafi-lambda-calculus
version:             0.1.0.0
github:              "Mafii/mafi-lambda-calculus"
license:             "WTFPL"
author:              "Mathias Fischler"
copyright:           "2022-2023 Mathias Fischler"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mafi-lambda-calculus#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- transformers

ghc-options:
- -Wincomplete-patterns
- -Wunused-imports
- -Wunused-matches

library:
  source-dirs: src

executables:
  mafi-lambda-calculus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mafi-lambda-calculus

tests:
  mafi-lambda-calculus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mafi-lambda-calculus
    - hspec

